### ISSUE TITLE
SPM Support

### ISSUE THREAD

**Issue by SocialKitLtd** [unsplash/unsplash-photopicker-ios#38]
Hey there,

We are upgrading our dependency manager to SPM. We would love support for Unsplash as well. Thanks!

**Comment by Claeysson** [comment]
I would also like to see SPM support 👍

**Comment by puelocesar** [comment]
There's even already a open Pull Request (#27), devs just need to accept it

**Comment by Kondamon** [comment]
Hi @ocollet!

First of all, thank you for this great framework!

May I kindly ask if Swift Package Manager support is planned to be added to this excellent framework as well? Since Xcode 12.5 it is really worth adding SPM support. A pull request can be found here: https://github.com/unsplash/unsplash-photopicker-ios/pull/27


Thank you!

**Comment by ocollet** [comment]
I just released a new version, 1.2.0, that adds support for SPM and a few fixes.
Sorry for being late on this.
