### ISSUE TITLE
Support for VisionOS

### ISSUE THREAD

**Issue by Vaberer** [unsplash/unsplash-photopicker-ios#59]
There are couple of errors for VisionOS. It requires small changes to make the VisionOS work.
Do you plan to fix these issues?

![Screenshot 2024-06-17 at 13 23 12](https://github.com/unsplash/unsplash-photopicker-ios/assets/8090436/febfcf51-0b0a-445a-ab09-15d758ef583a)

**Comment by ocollet** [comment]
I built a brand new image picker in SwiftUI that works on iOS, macOS, and visionOS. It has the same initializers and methods as [PhotosPicker](https://developer.apple.com/documentation/photokit/photospicker).

It's almost ready for release, I just need to clean up the code and write the documentation, which I plan to do in the coming weeks. It will be a new repo and I will deprecate this one.

**Comment by Vaberer** [comment]
Hello @ocollet, wow that's very great news. I'm looking forward to check it

**Comment by alschmut** [comment]
Hi there @ocollet ;) I just found the unsplash photo service and with it this iOS SDK. I quite like that this SDK exists, so that I don't have to integrate the unsplash APIs myself, but I do fear that this repository might not be maintained anymore. Do you still plan to open source your newer internal SwiftUI unsplash photo picker? :)
